### ISSUE TITLE
docker-friendly configuration options

### ISSUE THREAD

**Issue by PhilsLab** [ngoduykhanh/PowerDNS-Admin#540]
So, I had _a bit_ of struggle configuring this application via docker/docker-compose with environment variables. Most of them don't work or only work under special conditions.

The only way I got this to run is with the following optimized custom docker-compose.yml:
```yaml
version: '2.1'

services:
  pda-server:
    image: ngoduykhanh/powerdns-admin:latest
    restart: always
    depends_on:
    - pda-db
    ports:
    - 80:80
    environment:
    # Manually set up the PowerDNS API to: http://pdns-server:8081
    - SQLALCHEMY_DATABASE_URI=mysql://pda:PdaPassword!@pda-db/pda

  pda-db:
    image: mysql:5.7
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    volumes:
    - ./data/admin-db:/var/lib/mysql
    environment:
    - MYSQL_DATABASE=pda
    - MYSQL_USER=pda
    - MYSQL_PASSWORD=PdaPassword!
    - MYSQL_RANDOM_ROOT_PASSWORD=1

  pdns-server:
    image: psitrax/powerdns
    restart: always
    depends_on:
    - pdns-db
    ports:
    - "53:53/tcp"
    - "53:53/udp"
    command:
    - --api=yes
    - --api-key=7fb943d7-bcd9-4763-86c9-c34676f7c011
    - --webserver-address=0.0.0.0
    - --webserver-allow-from=0.0.0.0/0
    environment:
    - MYSQL_HOST=pdns-db
    - MYSQL_USER=pdns
    - MYSQL_PASS=PdnsPassword!

  pdns-db:
    image: mysql:5.7
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    volumes:
    - ./data/pdns-db:/var/lib/mysql
    environment:
    - MYSQL_DATABASE=pdns
    - MYSQL_USER=pdns
    - MYSQL_PASSWORD=PdnsPassword!
    - MYSQL_RANDOM_ROOT_PASSWORD=1
```

What didn't work?
- There is no "production" environment
- Setting up the database with the given environment variables: **PDA_DB_HOST, PDA_DB_NAME, PDA_DB_USER, PDA_DB_PASSWORD, PDA_DB_PORT** (using **SQLALCHEMY_DATABASE_URI**)
- Connecting to the PowerDNS API with the given environment variables: **PDNS_HOST, PDNS_API_KEY** (had to be configured manually)
- The example docker-compose.yml misses **MYSQL_RANDOM_ROOT_PASSWORD=1** for the MySQL containers, they won't even spin up
- Many config keys are redundant with the config.py
- Most of the ports are NATed to the public even though they are just used for internal communication

To make it fully docker-capable, PowerDNS-Admin should be ready-to-run by only setting environment variables.

Are there any plans to enhance the configuration for Docker?
