### ISSUE TITLE
docker-compose can not start docker image anymore

### ISSUE THREAD

**Issue by croessner** [ngoduykhanh/PowerDNS-Admin#594]
Hi,

first of all thaks for fixing the docker image. Unfortunately I am not able to get the docker image running anymore.

I tried to merge my docker-compose.yml file with yours, as yours has changed a lot. Maybe I am missing some part and you could give me a hint :-)

```
version: "3"

services:
  app:
    image: powerdns-admin:latest
    container_name: powerdns_admin
    ports:
      - "9191:9191"
      - "9393:9393"
    #volumes:
    #  # Code
    #  - .:/powerdns-admin/
    #  - "./configs/${ENVIRONMENT}.py:/powerdns-admin/config.py"
    #  # Assets dir volume
    #  - powerdns-admin-assets:/powerdns-admin/app/static
    #  - powerdns-admin-assets2:/powerdns-admin/node_modules
    #  - powerdns-admin-assets3:/powerdns-admin/logs
    #  - ./app/static/custom:/powerdns-admin/app/static/custom
    logging:
      driver: json-file
      options:
        max-size: 50m
    networks:
      - pda_default
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql://${PDA_DB_USER}:${PDA_DB_PASSWORD}@${PDA_DB_HOST}/${PDA_DB_NAME}
      - GUINCORN_TIMEOUT=60
      - GUNICORN_WORKERS=2
      - GUNICORN_LOGLEVEL=DEBUG
      - PDNS_HOST=${PDNS_HOST}
      - PDNS_API_KEY=${PDNS_API_KEY}
    restart: unless-stopped

networks:
  pda_default:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: pda0
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24

#volumes:
#  powerdns-admin-assets:
#  powerdns-admin-assets2:
#  powerdns-admin-assets3:
```

I have an dot-env file looking like this:

```
PDA_DB_HOST=192.168.0.210
PDA_DB_NAME=pda
PDA_DB_USER=pda
PDA_DB_PASSWORD=***password*removed***
PDA_DB_PORT=3306

PDNS_HOST=192.168.0.210
PDNS_API_KEY=***password*removed***
PDNS_WEBSERVER_ALLOW_FROM=0.0.0.0
```

When trying to start the container like this:

```
root@ns1 src/PowerDNS-Admin (rns-1 *%) » docker-compose up -d; docker-compose logs -f
```

I get errors like this:

```
Creating network "powerdns-admin_pda_default" with driver "bridge"
Creating powerdns_admin ... done
Attaching to powerdns_admin
powerdns_admin |  * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
powerdns_admin | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
powerdns_admin | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
powerdns_admin | ERROR [root] Error: Multiple head revisions are present for given argument 'head'; please specify a specific target revision, '<branchname>@head' to narrow to a specific head, or 'heads' for all heads
root@ns1 src/PowerDNS-Admin (rns-1 *%) »
```

Unfortunately I have no idea what to do here :-) Do you think, you could provide a very little README for the docker stuff inside the docker folder? I have no idea where to define the API key stuff for powerdns now. You docker-compose.yml does not have variables for this. I am a little bit stuck and would be very happy to have powerdns-admin running again.

Best wishes

Christian

**Comment by ngoduykhanh** [comment]
Hi @croessner , 

I see you are having this error
```
powerdns_admin | ERROR [root] Error: Multiple head revisions are present for given argument 'head'; please specify a specific target revision, '<branchname>@head' to narrow to a specific head, or 'heads' for all heads
```
It looks like your migration scripts are broken somehow. Are you using the latest source code to build the Docker image? You can also try with my image from [Docker hub](https://hub.docker.com/r/ngoduykhanh/powerdns-admin) to see if it fixes your issue.

Regarding pdns API key stuff, it is stored in the PDA DB, so you will able to configure it after you login as admin in **Settings > PDNS** menu.

**Comment by ngoduykhanh** [comment]
I found an article [here](https://blog.jerrycodes.com/multiple-heads-in-alembic-migrations/) that can explain to you about that error in case you are interested in fixing it.

**Comment by croessner** [comment]
Thanks for your answer. Unfortunately that did not help.

I have removed the source folder and git cloned it newly. Then I put back my saved docker-compose.yml file and tried again. This time with your docker image. But it produces the same error. I have no idea what to do right now.

```
docker-compose up -d; docker-compose logs -f
Creating network "powerdns-admin_pda_default" with driver "bridge"
Creating powerdns_admin ... done
Attaching to powerdns_admin
powerdns_admin | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
powerdns_admin | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
powerdns_admin | ERROR [root] Error: Can't locate revision identified by 'bf5e40f2dedc'
```

docker-compose.yml without dot-env file:

```
version: "3"

services:
  app:
    image: ngoduykhanh/powerdns-admin:latest
    container_name: powerdns_admin
    ports:
      - "9191:9191"
    logging:
      driver: json-file
      options:
        max-size: 5m
    networks:
      - pda_default
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql://pda:***pw-removed***@192.168.0.210/pda
      - GUINCORN_TIMEOUT=60
      - GUNICORN_WORKERS=2
      - GUNICORN_LOGLEVEL=DEBUG
    restart: unless-stopped

networks:
  pda_default:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: pda0
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
```
