### ISSUE TITLE
got a 400 bad request when add new domain

### ISSUE THREAD

**Issue by baalchina** [ngoduykhanh/PowerDNS-Admin#749]
Hi all, I got a 400 bad request when add new domain.

![image](https://user-images.githubusercontent.com/3983019/83596010-24d77980-a596-11ea-914c-0859a11a5c7b.png)

My  pdns v4.1.11 runs in centos 7 , and pdns-admin runs in docker.
I can open pdns-admin webui (http://localhost:9191), every menu works fine except the new domain.

pdns webui works fine:
![image](https://user-images.githubusercontent.com/3983019/83596112-649e6100-a596-11ea-85d9-df1db8e93a5f.png)

so, how can I find where the problem is?

Thanks.

**Comment by RoeiGanor** [comment]
It is usually problem connecting to the pdns api.
We will appreciate it if you'll share your API setting.
Also, I experienced it once when my pdns DB scheme was 4.3 and my pdns instance was 4.1.

**Comment by baalchina** [comment]
> We will appreciate it if you'll share your API setting.

thanks.

in my pdns.conf, i only uncomment the 
api=yes
api-key=key

and all other are default.

The setting of pdns like this:

![image](https://user-images.githubusercontent.com/3983019/83644147-8a9e2280-a5e3-11ea-8ed7-13e43338cb27.png)


btw, shoud I install pdns-backend? I had already installed pdns-backend-sqlite

**Comment by RoeiGanor** [comment]
Can you also share the docker logs of this container?

**Comment by MrGeneration** [comment]
You can't talk to localhost of your host when coming from inside of a docker container.
Instead you'll need to talk to the ip address of your host of the docker network.

I had similar issues when I was fiddling around.
For this I adjusted my docker-compose as follows (I only present relevant parts):

Le service
```
version: '3'
services:
    pdns-admin:
       image: ngoduykhanh/powerdns-admin:latest
       container_name: powerdns_admin
       restart: always
       networks:
           pdns-net:
             ipv4_address: 172.16.16.14
       ports:
          - "127.0.0.1:9191:80"

    [....]
```

Network (while 172.16.16.1 will be the host IP):
```
    [....]

networks:
   pdns-net:
      driver: bridge
      ipam:
         driver: default
         config:
           - subnet: 172.16.16.0/24
```

Basically you don't need to change your docker net if you already have a static setup or can ensure that it doesn't change. Above is just my way of enforcing specific static addresses. Keep in mind to tell your firewall that it's supposed to allow such traffic, in case you're blocking.
